from __future__ import annotations

BRANCH_RUN_BATCH_REQUEST = "BRANCH_RUN_BATCH_REQUEST"
MAIN_BATCH_PROGRESS = "MAIN_BATCH_PROGRESS"
MAIN_BATCH_TASK_RESULT = "MAIN_BATCH_TASK_RESULT"
MAIN_BATCH_FINISHED = "MAIN_BATCH_FINISHED"
MAIN_BATCH_REJECTED = "MAIN_BATCH_REJECTED"
