# core/Constants.py

# Time / Frames
NEVER_USED_TIME = -9999.0
DEFAULT_CD = 0.0
DEFAULT_TOTAL_FRAMES = 0

# Elements
ELEMENT_PHYSICAL = '物理'
ELEMENT_PYRO = '火'
ELEMENT_HYDRO = '水'
ELEMENT_CRYO = '冰'
ELEMENT_ELECTRO = '雷'
ELEMENT_ANEMO = '风'
ELEMENT_GEO = '岩'
ELEMENT_DENDRO = '草'
ELEMENT_NONE = '无'

ELEMENT_ORDER = [ELEMENT_HYDRO, ELEMENT_PYRO, ELEMENT_CRYO]

# Attributes
ATTR_HP = '生命值'
ATTR_HP_PERCENT = '生命值%'
ATTR_FIXED_HP = '固定生命值'
ATTR_ATK = '攻击力'
ATTR_ATK_PERCENT = '攻击力%'
ATTR_FIXED_ATK = '固定攻击力'
ATTR_DEF = '防御力'
ATTR_DEF_PERCENT = '防御力%'
ATTR_FIXED_DEF = '固定防御力'
ATTR_EM = '元素精通'
ATTR_CRIT_RATE = '暴击率'
ATTR_CRIT_DMG = '暴击伤害'
ATTR_ER = '元素充能效率'
ATTR_HEAL_BONUS = '治疗加成'
ATTR_INCOMING_HEAL_BONUS = '受治疗加成'
ATTR_DMG_BONUS = '伤害加成'
ATTR_PYRO_DMG_BONUS = '火元素伤害加成'
ATTR_HYDRO_DMG_BONUS = '水元素伤害加成'
ATTR_ELECTRO_DMG_BONUS = '雷元素伤害加成'
ATTR_CRYO_DMG_BONUS = '冰元素伤害加成'
ATTR_GEO_DMG_BONUS = '岩元素伤害加成'
ATTR_ANEMO_DMG_BONUS = '风元素伤害加成'
ATTR_DENDRO_DMG_BONUS = '草元素伤害加成'
ATTR_PHYSICAL_DMG_BONUS = '物理伤害加成'
ATTR_REACTION_MULTIPLIER = '反应系数'
ATTR_REACTION_BONUS = '反应系数提高'
ATTR_LEVEL_MULTIPLIER = '等级系数'
ATTR_INDEPENDENT_DMG_BONUS = '独立伤害加成'
ATTR_FIXED_DMG_BONUS = '固定伤害基础值加成'
ATTR_DMG_MULTIPLIER = '伤害倍率'
ATTR_ELEMENT_RES = '元素抗性'
ATTR_DEF_REDUCTION = '防御力减免'

SUFFIX_ELEMENT = '元素'

# Skill Names
SKILL_NAME_NORMAL = "普通攻击"
SKILL_NAME_CHARGED = "重击"
SKILL_NAME_PLUNGING = "下落攻击"
SKILL_NAME_DASH = "冲刺"
SKILL_NAME_JUMP = "跳跃"
SKILL_NAME_ELEMENTAL_SKILL = "元素战技"
SKILL_NAME_ELEMENTAL_BURST = "元素爆发"

DAMAGE_TYPE_REACTION = "剧变反应"
REACTION_AGGRIVATE = "激化反应"
DAMAGE_BOOST_AGGRIVATE = "激化提升"
DAMAGE_BOOST_REACTION = "反应伤害提高"


# Combat
PLUNGING_HEIGHT_THRESHOLD = 80
FALLING_SPEED = 5

PLUNGING_HIGH = '高空'
PLUNGING_LOW = '低空'
PLUNGING_DMG_DURING = '下坠期间伤害'
PLUNGING_DMG_IMPACT_LOW = '低空坠地冲击伤害'
PLUNGING_DMG_IMPACT_HIGH = '高空坠地冲击伤害'
